#ifndef __FSM_H
#define __FSM_H
#include "stm32f4xx.h"

// 机器人的主状态
typedef enum ROBOT_STATE_ITEMS
{
	PREPARATION,
	
	MOVING_URTUU_TO_RZ,
	MOVING_LINE1_TO_RZ,
	MOVING_RZ_TO_S1,
	MOVING_LINE1_TO_S1,
	MOVING_LINE1_TO_S2,
	MOVING_LINE1_TO_S3,
	MOVING_S1_TO_PZ,
	MOVING_PZ_TO_TZ,
	MOVING_S1_TO_TZ,
	MOVING_S2_TO_TZ,
	MOVING_S3_TO_TZ,
	MOVING_TZ_TO_S1,
	MOVING_TZ_TO_S2,
	MOVING_TZ_TO_S3,
	
	RELAY,
	
	GRASPING,
	
	THROWING,
}ROBOT_STATE_ITEMS;

// 移动的具体状态
typedef enum MOVING_STATE_ITEMS
{
	MOVING_STOP,
	MOVING_GOING,
	MOVING_ARRIVED,
}MOVING_STATE_ITEMS;

// 交接的具体状态
typedef enum RELAY_STATE_ITEMS
{
	RELAY_STOP,
	RELAY_START,
	RELAY_SUCCEEDED,
}RELAY_STATE_ITEMS;

// 抓取的具体状态
typedef enum GRASPING_STATE_ITEMS
{
	GRASPING_STOP,
	GRASPING_START,
	GRASPING_SUCCEEDED,
}GRASPING_STATE_ITEMS;

// 抛投的具体状态
typedef enum THROWING_STATE_ITEMS
{
	THROWING_STOP,
	THROWING_START,
	THROWING_SUCCEEDED,
}THROWING_STATE_ITEMS;

// 准备阶段可选择的模式
typedef enum OPTAINAL_MODE_ITEMS
{
	MODE_UNKNOWN,
	URTUU_TO_RZ,
	LINE1_TO_RZ,
	LINE1_TO_S1,
	LINE1_TO_S2,
	LINE1_TO_S3,
}OPTAINAL_MODE_ITEMS;

// MR2是否到达高山驿的状态
typedef enum MR2_STATE_ITEMS
{
	NOT_ARRIVED,
	ARRIVED,
}MR2_STATE_ITEMS;

// 投掷完毕后（或兽骨重试）选择下一个投掷的兽骨
typedef enum SHAGAI_CHOICE_ITEMS
{
	SHAGAI_UNKNOWN,
	SHAGAI1,
	SHAGAI2,
	SHAGAI3,
}SHAGAI_CHOICE_ITEMS;

void FSM_finite_state_machine(void);

extern enum ROBOT_STATE_ITEMS NOW_STATE;

#endif
