#include "main.h"


// 初始化各个状态值
ROBOT_STATE_ITEMS NOW_STATE = PREPARATION;
ROBOT_STATE_ITEMS LAST_STATE = PREPARATION;
MOVING_STATE_ITEMS MOVING_STATE = MOVING_STOP;
RELAY_STATE_ITEMS RELAY_STATE = RELAY_STOP;
GRASPING_STATE_ITEMS GRASPING_STATE = GRASPING_STOP;
THROWING_STATE_ITEMS THROWING_STATE = THROWING_STOP;
OPTAINAL_MODE_ITEMS OPTAINAL_MODE = MODE_UNKNOWN;
MR2_STATE_ITEMS MR2_STATE = NOT_ARRIVED;  // 初始时默认MR2未到达高山驿
SHAGAI_CHOICE_ITEMS SHAGAI_CHOICE = SHAGAI_UNKNOWN;


// 有限状态机
void FSM_finite_state_machine(void)
{
	
	switch( NOW_STATE )
	{
		// 准备阶段进行模式选择
		case PREPARATION :
		{
			if(OPTAINAL_MODE == MODE_UNKNOWN)
			{
				// 这里应该给操作手一个提示，提示他可以选择模式
			}
			else
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_GOING;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_STOP;
				
				switch(OPTAINAL_MODE)
				{
					case URTUU_TO_RZ : NOW_STATE = MOVING_URTUU_TO_RZ; break;
					case LINE1_TO_RZ : NOW_STATE = MOVING_LINE1_TO_RZ; break;
					case LINE1_TO_S1 : NOW_STATE = MOVING_LINE1_TO_S1; break;
					case LINE1_TO_S2 : NOW_STATE = MOVING_LINE1_TO_S2; break;
					case LINE1_TO_S3 : NOW_STATE = MOVING_LINE1_TO_S3; break;
				}
			}
		}
		break;
		
		// 从龙门驿到交接点移动
		case MOVING_URTUU_TO_RZ :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_START;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = RELAY;
			}
		}
		break;
		
		// 交接
		case RELAY :
		{
			if(RELAY_STATE == RELAY_SUCCEEDED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_GOING;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = MOVING_RZ_TO_S1;
			}
		}
		break;
		
		// 从交接点到兽骨1放置点移动
		case MOVING_RZ_TO_S1 :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_START;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = GRASPING;
			}
		}
		break;
		
		// 抓取兽骨
		case GRASPING :
		{
			if(GRASPING_STATE == GRASPING_SUCCEEDED)
			{
				MOVING_STATE = MOVING_GOING;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_STOP;
				
				switch(LAST_STATE)
				{
					case MOVING_RZ_TO_S1: NOW_STATE = MOVING_S1_TO_PZ; break;
					case MOVING_TZ_TO_S1: NOW_STATE = MOVING_S1_TO_TZ; break;
					case MOVING_LINE1_TO_S1: 
							 {
								 if(MR2_STATE == NOT_ARRIVED) NOW_STATE = MOVING_S1_TO_PZ;
								 else if(MR2_STATE == ARRIVED) NOW_STATE = MOVING_S1_TO_TZ;
								 break;
							 }
					case MOVING_LINE1_TO_S2: NOW_STATE = MOVING_S2_TO_TZ; break;
					case MOVING_TZ_TO_S2: NOW_STATE = MOVING_S2_TO_TZ; break;
					case MOVING_LINE1_TO_S3: NOW_STATE = MOVING_S3_TO_TZ; break;
					case MOVING_TZ_TO_S3: NOW_STATE = MOVING_S3_TO_TZ; break;
				}
				LAST_STATE = GRASPING;
			}
		}
		break;
		
		// 从兽骨1放置点到准备点移动
		case MOVING_S1_TO_PZ :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_STOP;
				if(MR2_STATE == ARRIVED)
				{
					LAST_STATE = NOW_STATE;
					NOW_STATE = MOVING_PZ_TO_TZ;
				}
				else if(MR2_STATE == NOT_ARRIVED)
				{
					
				}
			}
		}
		break; 
		
		// 从准备点到投掷点
		case MOVING_PZ_TO_TZ :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_START;
				NOW_STATE = THROWING;
			}
		}
		break;
		
		// 投掷
		case THROWING :
		{
			if(THROWING_STATE == THROWING_SUCCEEDED)
			{
				THROWING_STATE = THROWING_STOP;
				
				if(SHAGAI_CHOICE == SHAGAI_UNKNOWN)
				{
					
				}
				
				else
				{
					LAST_STATE = NOW_STATE;
					MOVING_STATE = MOVING_GOING;
					RELAY_STATE = RELAY_STOP;
					GRASPING_STATE = GRASPING_STOP;
					
					switch(SHAGAI_CHOICE)
					{
						case SHAGAI1: NOW_STATE = MOVING_TZ_TO_S1; break;
						case SHAGAI2: NOW_STATE = MOVING_TZ_TO_S2; break;
						case SHAGAI3: NOW_STATE = MOVING_TZ_TO_S3; break;				
					}
					break;
				}
			}
		}
		break;
		
		// 从投掷点到兽骨1放置点移动
		case MOVING_TZ_TO_S1 :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_START;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = GRASPING;
			}
		}
		break;
		
		// 从投掷点到兽骨2放置点移动
		case MOVING_TZ_TO_S2 :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_START;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = GRASPING;
			}
		}
		break;
		
		// 从投掷点到兽骨3放置点移动
		case MOVING_TZ_TO_S3 :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_START;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = GRASPING;
			}
		}
		break;
		
		// 从界线1到交接点移动
		case MOVING_LINE1_TO_RZ :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_START;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = RELAY;
			}
		}
		break;
		
		// 从界线1到兽骨1放置点移动
		case MOVING_LINE1_TO_S1 :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_START;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = GRASPING;
			}
		}
		break;
		
		// 从界线1到兽骨2放置点移动
		case MOVING_LINE1_TO_S2 :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_START;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = GRASPING;
			}
		}
		break;
		
		// 从界线1到兽骨3放置点移动
		case MOVING_LINE1_TO_S3 :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_START;
				THROWING_STATE = THROWING_STOP;
				NOW_STATE = GRASPING;
			}
		}
		break;
		
		// 从兽骨1放置点到投掷点移动
		case MOVING_S1_TO_TZ :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_START;
				NOW_STATE = THROWING;
			}
		}
		break;
		
		// 从兽骨2放置点到投掷点移动
		case MOVING_S2_TO_TZ :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_START;
				NOW_STATE = THROWING;
			}
		}
		break;
		
		// 从兽骨3放置点到投掷点移动
		case MOVING_S3_TO_TZ :
		{
			if(MOVING_STATE == MOVING_ARRIVED)
			{
				LAST_STATE = NOW_STATE;
				MOVING_STATE = MOVING_STOP;
				RELAY_STATE = RELAY_STOP;
				GRASPING_STATE = GRASPING_STOP;
				THROWING_STATE = THROWING_START;
				NOW_STATE = THROWING;
			}
		}
		break;
	}
}
